[project]
name = "zolon-tgif-photo-compliance-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.67",
    "flask>=2.3.0",
    "pillow>=10.0.0",
    "pillow-heif>=0.13.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "werkzeug>=2.3.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
